github: [academicpal, harihara7]
patreon: academicpal
open_collective: academicpal
ko_fi: academicpal
tidelift: npm/academicpal
community_bridge: academicpal
liberapay: academicpal
issuehunt: academicpal
lfx_crowdfunding: academicpal
polar: academicpal
buy_me_a_coffee: academicpal
thanks_dev: academicpal
custom: ['https://academicpal.in/donate', 'https://www.paypal.me/academicpal']
